
package itmo.web_services.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BooksWebService", targetNamespace = "http://service.web_services.itmo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BooksWebService {


    /**
     * 
     * @param publishingHouse
     * @param title
     * @return
     *     returns java.util.List<itmo.web_services.service.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBooksByTitleAndPublishingHouse", targetNamespace = "http://service.web_services.itmo/", className = "itmo.web_services.service.GetBooksByTitleAndPublishingHouse")
    @ResponseWrapper(localName = "getBooksByTitleAndPublishingHouseResponse", targetNamespace = "http://service.web_services.itmo/", className = "itmo.web_services.service.GetBooksByTitleAndPublishingHouseResponse")
    @Action(input = "http://service.web_services.itmo/BooksWebService/getBooksByTitleAndPublishingHouseRequest", output = "http://service.web_services.itmo/BooksWebService/getBooksByTitleAndPublishingHouseResponse")
    public List<Book> getBooksByTitleAndPublishingHouse(
        @WebParam(name = "title", targetNamespace = "")
        String title,
        @WebParam(name = "publishingHouse", targetNamespace = "")
        String publishingHouse);

    /**
     * 
     * @param author
     * @param publishingHouse
     * @return
     *     returns java.util.List<itmo.web_services.service.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBooksByAuthorAndPublishingHouse", targetNamespace = "http://service.web_services.itmo/", className = "itmo.web_services.service.GetBooksByAuthorAndPublishingHouse")
    @ResponseWrapper(localName = "getBooksByAuthorAndPublishingHouseResponse", targetNamespace = "http://service.web_services.itmo/", className = "itmo.web_services.service.GetBooksByAuthorAndPublishingHouseResponse")
    @Action(input = "http://service.web_services.itmo/BooksWebService/getBooksByAuthorAndPublishingHouseRequest", output = "http://service.web_services.itmo/BooksWebService/getBooksByAuthorAndPublishingHouseResponse")
    public List<Book> getBooksByAuthorAndPublishingHouse(
        @WebParam(name = "author", targetNamespace = "")
        String author,
        @WebParam(name = "publishingHouse", targetNamespace = "")
        String publishingHouse);

    /**
     * 
     * @return
     *     returns java.util.List<itmo.web_services.service.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBooks", targetNamespace = "http://service.web_services.itmo/", className = "itmo.web_services.service.GetBooks")
    @ResponseWrapper(localName = "getBooksResponse", targetNamespace = "http://service.web_services.itmo/", className = "itmo.web_services.service.GetBooksResponse")
    @Action(input = "http://service.web_services.itmo/BooksWebService/getBooksRequest", output = "http://service.web_services.itmo/BooksWebService/getBooksResponse")
    public List<Book> getBooks();

    /**
     * 
     * @param title
     * @return
     *     returns java.util.List<itmo.web_services.service.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBooksByTitle", targetNamespace = "http://service.web_services.itmo/", className = "itmo.web_services.service.GetBooksByTitle")
    @ResponseWrapper(localName = "getBooksByTitleResponse", targetNamespace = "http://service.web_services.itmo/", className = "itmo.web_services.service.GetBooksByTitleResponse")
    @Action(input = "http://service.web_services.itmo/BooksWebService/getBooksByTitleRequest", output = "http://service.web_services.itmo/BooksWebService/getBooksByTitleResponse")
    public List<Book> getBooksByTitle(
        @WebParam(name = "title", targetNamespace = "")
        String title);

    /**
     * 
     * @param author
     * @return
     *     returns java.util.List<itmo.web_services.service.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBooksByAuthor", targetNamespace = "http://service.web_services.itmo/", className = "itmo.web_services.service.GetBooksByAuthor")
    @ResponseWrapper(localName = "getBooksByAuthorResponse", targetNamespace = "http://service.web_services.itmo/", className = "itmo.web_services.service.GetBooksByAuthorResponse")
    @Action(input = "http://service.web_services.itmo/BooksWebService/getBooksByAuthorRequest", output = "http://service.web_services.itmo/BooksWebService/getBooksByAuthorResponse")
    public List<Book> getBooksByAuthor(
        @WebParam(name = "author", targetNamespace = "")
        String author);

    /**
     * 
     * @param min
     * @param author
     * @return
     *     returns java.util.List<itmo.web_services.service.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBooksByAuthorAndMinPages", targetNamespace = "http://service.web_services.itmo/", className = "itmo.web_services.service.GetBooksByAuthorAndMinPages")
    @ResponseWrapper(localName = "getBooksByAuthorAndMinPagesResponse", targetNamespace = "http://service.web_services.itmo/", className = "itmo.web_services.service.GetBooksByAuthorAndMinPagesResponse")
    @Action(input = "http://service.web_services.itmo/BooksWebService/getBooksByAuthorAndMinPagesRequest", output = "http://service.web_services.itmo/BooksWebService/getBooksByAuthorAndMinPagesResponse")
    public List<Book> getBooksByAuthorAndMinPages(
        @WebParam(name = "author", targetNamespace = "")
        String author,
        @WebParam(name = "min", targetNamespace = "")
        int min);

    /**
     * 
     * @param publishingHouse
     * @return
     *     returns java.util.List<itmo.web_services.service.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBooksByPublishingHouse", targetNamespace = "http://service.web_services.itmo/", className = "itmo.web_services.service.GetBooksByPublishingHouse")
    @ResponseWrapper(localName = "getBooksByPublishingHouseResponse", targetNamespace = "http://service.web_services.itmo/", className = "itmo.web_services.service.GetBooksByPublishingHouseResponse")
    @Action(input = "http://service.web_services.itmo/BooksWebService/getBooksByPublishingHouseRequest", output = "http://service.web_services.itmo/BooksWebService/getBooksByPublishingHouseResponse")
    public List<Book> getBooksByPublishingHouse(
        @WebParam(name = "publishingHouse", targetNamespace = "")
        String publishingHouse);

    /**
     * 
     * @param author
     * @param title
     * @return
     *     returns java.util.List<itmo.web_services.service.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBooksByTitleAndAuthor", targetNamespace = "http://service.web_services.itmo/", className = "itmo.web_services.service.GetBooksByTitleAndAuthor")
    @ResponseWrapper(localName = "getBooksByTitleAndAuthorResponse", targetNamespace = "http://service.web_services.itmo/", className = "itmo.web_services.service.GetBooksByTitleAndAuthorResponse")
    @Action(input = "http://service.web_services.itmo/BooksWebService/getBooksByTitleAndAuthorRequest", output = "http://service.web_services.itmo/BooksWebService/getBooksByTitleAndAuthorResponse")
    public List<Book> getBooksByTitleAndAuthor(
        @WebParam(name = "title", targetNamespace = "")
        String title,
        @WebParam(name = "author", targetNamespace = "")
        String author);

    /**
     * 
     * @param from
     * @param to
     * @return
     *     returns java.util.List<itmo.web_services.service.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBooksByPagesRange", targetNamespace = "http://service.web_services.itmo/", className = "itmo.web_services.service.GetBooksByPagesRange")
    @ResponseWrapper(localName = "getBooksByPagesRangeResponse", targetNamespace = "http://service.web_services.itmo/", className = "itmo.web_services.service.GetBooksByPagesRangeResponse")
    @Action(input = "http://service.web_services.itmo/BooksWebService/getBooksByPagesRangeRequest", output = "http://service.web_services.itmo/BooksWebService/getBooksByPagesRangeResponse")
    public List<Book> getBooksByPagesRange(
        @WebParam(name = "from", targetNamespace = "")
        int from,
        @WebParam(name = "to", targetNamespace = "")
        int to);

    /**
     * 
     * @param max
     * @param author
     * @return
     *     returns java.util.List<itmo.web_services.service.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBooksByAuthorAndMaxPages", targetNamespace = "http://service.web_services.itmo/", className = "itmo.web_services.service.GetBooksByAuthorAndMaxPages")
    @ResponseWrapper(localName = "getBooksByAuthorAndMaxPagesResponse", targetNamespace = "http://service.web_services.itmo/", className = "itmo.web_services.service.GetBooksByAuthorAndMaxPagesResponse")
    @Action(input = "http://service.web_services.itmo/BooksWebService/getBooksByAuthorAndMaxPagesRequest", output = "http://service.web_services.itmo/BooksWebService/getBooksByAuthorAndMaxPagesResponse")
    public List<Book> getBooksByAuthorAndMaxPages(
        @WebParam(name = "author", targetNamespace = "")
        String author,
        @WebParam(name = "max", targetNamespace = "")
        int max);

}
